### PR TITLE
Calculate the View on the base-2 logarithm

### PR DESCRIPTION
**Pull request by das399igste**
the adjustments enable the clear display of logarithmically increasing values

### CODE REVIEW

**Comment by hotNipi** [comment]
Hi.
I have tried your modifications and they do work but I have some doubts about it. I can't figure out the real life usage of this feature. 
Can you please point out where and how it can be useful.

**Comment by das399igste** [comment]
Hi,
I measure Total Volatile Organic Compounds (TVOC) with a Xiaomi AAQS-S01 
air quality monitor.

I would like to display the values in such a way that the first steps 
are also clearly resolved. With a linear representation, the low values 
cannot be resolved.





Am 24.02.2022 um 08:32 schrieb hotNipi:

**Comment by das399igste** [comment]
Am 24.02.2022 um 08:32 schrieb hotNipi:
    
    
    Following the human perception, the
      German Federal Environmental Agency translates TVOC concentration
      (parts per billion) on a logarithmic scale into five indoor air
      quality levels (IAQ), as shown in Table below.

**Comment by das399igste** [comment]
Am 24.02.2022 um 08:32 schrieb hotNipi:

**Comment by das399igste** [comment]
Am 24.02.2022 um 08:32 schrieb hotNipi:
    
    
    
    
      
      Hi.
        I have tried your modifications and they do work but I have some
        doubts about it. I can't figure out the real life usage of this
        feature.
        Can you please point out where and how it can be useful.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/hotNipi/node-red-contrib-ui-artless-gauge/pull/27#issuecomment-1049571809",
"url": "https://github.com/hotNipi/node-red-contrib-ui-artless-gauge/pull/27#issuecomment-1049571809",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
